/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 20:34:10 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.PriorityQueue;
import java.util.ServiceLoader;
import java.util.SortedSet;
import java.util.Stack;
import java.util.TreeSet;
import java.util.Vector;
import java.util.function.BiFunction;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.UnaryOperator;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.OptionGroup;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.AbstractHelpFormatter;
import org.apache.commons.cli.help.HelpAppendable;
import org.apache.commons.cli.help.HelpFormatter;
import org.apache.commons.cli.help.OptionFormatter;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextHelpAppendable;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AbstractHelpFormatter_ESTest extends AbstractHelpFormatter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      helpFormatter_Builder0.setOptionGroupSeparator("");
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      helpFormatter_Builder0.setOptionGroupSeparator("~OU:h^&$\"AOF{k2vR");
      Options options0 = new Options();
      helpFormatter0.toSyntaxOptions(options0);
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      helpFormatter_Builder0.setComparator(helpFormatter0.DEFAULT_COMPARATOR);
      Collection<Option> collection0 = options0.getOptions();
      options0.getOptions();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) collection0);
      helpFormatter0.printOptions(tableDefinition0);
      helpFormatter0.getOptionGroupSeparator();
      helpFormatter0.sort(options0);
      helpFormatter0.toArgName("");
      helpFormatter0.getTableDefinition(collection0);
      helpFormatter0.getComparator();
      HelpFormatter.builder();
      Option option0 = null;
      try {
        option0 = new Option("o}fs48A`dzV.v}OG?", true, "~OU:h^&$\"AOF{k2vR");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option 'o}fs48A`dzV.v}OG?' contains an illegal character : '}'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option((String) null, "usage: ", true, (String) null);
      OptionGroup optionGroup1 = optionGroup0.addOption(option0);
      option0.setLongOpt("ld'qI4+J:>O;D4*");
      optionGroup1.addOption(option0);
      String string0 = helpFormatter0.toSyntaxOptions(optionGroup1);
      assertEquals("[--ld'qI4+J:>O;D4* <arg> | --ld'qI4+J:>O;D4* <arg>]", string0);
      
      helpFormatter0.getOptionFormatBuilder();
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      Options options1 = options0.addRequiredOption((String) null, "usage: ", true, (String) null);
      List<Option> list0 = helpFormatter0.sort(options0);
      OptionFormatter.Builder optionFormatter_Builder0 = helpFormatter0.getOptionFormatBuilder();
      helpFormatter_Builder0.setOptionFormatBuilder(optionFormatter_Builder0);
      helpFormatter0.printHelp("w`2i**i3.f ", "5qT~ Kf;h", (Iterable<Option>) list0, (String) null, true);
      helpFormatter0.getTableDefinition(list0);
      helpFormatter0.toSyntaxOptions(options1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.getComparator();
      HelpFormatter helpFormatter1 = helpFormatter_Builder0.get();
      HelpFormatter helpFormatter2 = helpFormatter_Builder0.get();
      helpFormatter1.getOptionFormatBuilder();
      Options options0 = new Options();
      HashSet<Option> hashSet0 = new HashSet<Option>(12);
      Option option0 = null;
      hashSet0.add((Option) null);
      helpFormatter1.toSyntaxOptions(options0);
      helpFormatter2.toSyntaxOptions(options0);
      helpFormatter2.getOptionGroupSeparator();
      helpFormatter1.printHelp(" | ", " | ", options0, " | ", true);
      HelpFormatter.builder();
      helpFormatter1.getHelpAppendable();
      // Undeclared exception!
      try { 
        helpFormatter0.toSyntaxOptions((Iterable<Option>) hashSet0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.OptionFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      helpFormatter0.setSyntaxPrefix("usage: ");
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions((Options) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FileSystemHandling fileSystemHandling0 = new FileSystemHandling();
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      OptionFormatter.Builder optionFormatter_Builder0 = OptionFormatter.builder();
      OptionFormatter.Builder optionFormatter_Builder1 = optionFormatter_Builder0.setOptPrefix(":<!>'GMws2W<E5C'*");
      OptionFormatter.Builder optionFormatter_Builder2 = optionFormatter_Builder1.setOptArgSeparator(":<!>'GMws2W<E5C'*");
      Function<Option, String> function0 = OptionFormatter.COMPLEX_DEPRECATED_FORMAT;
      OptionFormatter.Builder optionFormatter_Builder3 = optionFormatter_Builder2.setDeprecatedFormatFunction(function0);
      optionFormatter_Builder2.build((Option) null);
      BiFunction<OptionFormatter, Boolean, String> biFunction0 = (BiFunction<OptionFormatter, Boolean, String>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(biFunction0).apply(any(org.apache.commons.cli.help.OptionFormatter.class) , anyBoolean());
      OptionFormatter.Builder optionFormatter_Builder4 = optionFormatter_Builder3.setSyntaxFormatFunction(biFunction0);
      optionFormatter_Builder1.setOptArgSeparator("w)-z 4HLCY-4_~|jye");
      optionFormatter_Builder4.setOptSeparator("%s %s");
      helpFormatter_Builder0.setOptionFormatBuilder(optionFormatter_Builder4);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Class<Option> class0 = Option.class;
      ServiceLoader<Option> serviceLoader0 = ServiceLoader.loadInstalled(class0);
      serviceLoader0.iterator();
      helpFormatter0.toSyntaxOptions((Iterable<Option>) serviceLoader0);
      Options options0 = new Options();
      helpFormatter0.sort(options0);
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setRequired(true);
      FileSystemHandling fileSystemHandling1 = new FileSystemHandling();
      Option option0 = new Option("$", false, "");
      OptionGroup optionGroup1 = optionGroup0.addOption(option0);
      optionGroup1.setSelected((Option) null);
      helpFormatter0.toSyntaxOptions(optionGroup1);
      helpFormatter0.getSyntaxPrefix();
      helpFormatter0.getHelpAppendable();
      HelpFormatter.builder();
      HelpFormatter.builder();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      TextHelpAppendable textHelpAppendable0 = (TextHelpAppendable)helpFormatter0.getHelpAppendable();
      textHelpAppendable0.setLeftPad((-2019));
      helpFormatter_Builder0.setHelpAppendable(textHelpAppendable0);
      helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter1 = new HelpFormatter(helpFormatter_Builder1);
      Options options0 = new Options();
      options0.getOptions();
      options0.hasOption("");
      helpFormatter_Builder0.setComparator(helpFormatter1.DEFAULT_COMPARATOR);
      // Undeclared exception!
      try { 
        helpFormatter1.printHelp("org.apache.commons.text.lookup.FunctionStringLookup", "org.apache.commons.text.lookup.FunctionStringLookup", options0, "W)!A0p72^02y72mwh", false);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      OptionFormatter.Builder optionFormatter_Builder0 = OptionFormatter.builder();
      optionFormatter_Builder0.toArgName("bC}KC1_VoC_p\"}a3");
      helpFormatter_Builder0.setOptionFormatBuilder(optionFormatter_Builder0);
      helpFormatter_Builder0.setComparator(helpFormatter0.DEFAULT_COMPARATOR);
      Function<Option, String> function0 = OptionFormatter.SIMPLE_DEPRECATED_FORMAT;
      OptionFormatter.Builder optionFormatter_Builder1 = optionFormatter_Builder0.setDeprecatedFormatFunction(function0);
      Options options0 = new Options();
      List<Option> list0 = helpFormatter0.sort(options0);
      BiFunction<OptionFormatter, Boolean, String> biFunction0 = (BiFunction<OptionFormatter, Boolean, String>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      optionFormatter_Builder0.setSyntaxFormatFunction(biFunction0);
      helpFormatter0.printOptions((Iterable<Option>) list0);
      helpFormatter0.setSyntaxPrefix("org.apache.commons.io.filefilter.DirectoryFileFilter");
      helpFormatter0.printOptions((Iterable<Option>) list0);
      List<Option> list1 = helpFormatter0.sort(options0);
      helpFormatter0.toSyntaxOptions((Iterable<Option>) list0);
      helpFormatter0.printHelp("5)zzEGC?8@?qrQm", "<bC}KC1_VoC_p\"}a3>", (Iterable<Option>) list1, "org.apache.commons.io.filefilter.DirectoryFileFilter", false);
      HelpFormatter.builder();
      helpFormatter0.getOptionFormatBuilder();
      OptionFormatter.Builder optionFormatter_Builder2 = helpFormatter0.getOptionFormatBuilder();
      assertNotSame(optionFormatter_Builder2, optionFormatter_Builder1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Vector<Option> vector0 = new Vector<Option>(5);
      Option option0 = null;
      vector0.add(0, (Option) null);
      TreeSet<TextHelpAppendable> treeSet0 = new TreeSet<TextHelpAppendable>();
      treeSet0.retainAll(vector0);
      vector0.containsAll(treeSet0);
      vector0.add((Option) null);
      // Undeclared exception!
      try { 
        helpFormatter0.sort((Iterable<Option>) vector0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.getComparator();
      HelpFormatter helpFormatter1 = helpFormatter_Builder0.get();
      helpFormatter_Builder0.get();
      helpFormatter1.getOptionFormatBuilder();
      Options options0 = new Options();
      FileSystemHandling.appendLineToFile((EvoSuiteFile) null, " | ");
      HashSet<Option> hashSet0 = new HashSet<Option>(12);
      Option option0 = null;
      hashSet0.add((Option) null);
      OptionGroup optionGroup0 = new OptionGroup();
      Function<Option, OptionGroup> function0 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn(optionGroup0).when(function0).apply(any(org.apache.commons.cli.Option.class));
      helpFormatter1.toSyntaxOptions((Iterable<Option>) hashSet0, function0);
      Function<Option, OptionGroup> function1 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(function1).apply(any(org.apache.commons.cli.Option.class));
      // Undeclared exception!
      try { 
        helpFormatter1.toSyntaxOptions((Iterable<Option>) hashSet0, function1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.OptionFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      helpFormatter0.printHelp("ek=", "@ (g%`Q]0 qS;KU}&", options0, "", true);
      helpFormatter0.getOptionGroupSeparator();
      TreeSet<Option> treeSet0 = new TreeSet<Option>();
      helpFormatter_Builder0.setOptionFormatBuilder((OptionFormatter.Builder) null);
      ArrayList<Option> arrayList0 = new ArrayList<Option>(treeSet0);
      Option option0 = null;
      try {
        option0 = new Option("@ (g%`Q]0 qS;KU}&", " | ", true, "5&AN|");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option '@ (g%`Q]0 qS;KU}&' contains an illegal character : ' '.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      HelpFormatter helpFormatter1 = helpFormatter_Builder1.get();
      Comparator<Option> comparator0 = helpFormatter1.getComparator();
      helpFormatter_Builder1.setComparator(comparator0);
      HelpFormatter helpFormatter2 = helpFormatter_Builder1.get();
      helpFormatter2.getSyntaxPrefix();
      helpFormatter1.getOptionGroupSeparator();
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>();
      PriorityQueue<Option> priorityQueue1 = new PriorityQueue<Option>(priorityQueue0);
      helpFormatter0.printOptions((Iterable<Option>) priorityQueue1);
      Function<Option, OptionGroup> function0 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter2.toSyntaxOptions((Iterable<Option>) priorityQueue0, function0);
      // Undeclared exception!
      try { 
        helpFormatter1.printHelp(" | ", "", (Options) null, " | ", false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = null;
      helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.toSyntaxOptions((Options) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      HelpAppendable helpAppendable0 = helpFormatter0.getHelpAppendable();
      helpFormatter_Builder0.setHelpAppendable(helpAppendable0);
      helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter1 = new HelpFormatter(helpFormatter_Builder1);
      Options options0 = new Options();
      Collection<Option> collection0 = options0.getOptions();
      options0.hasOption("");
      helpFormatter_Builder0.setComparator(helpFormatter1.DEFAULT_COMPARATOR);
      helpFormatter1.printHelp("org.apache.commons.text.lookup.FunctionStringLookup", "org.apache.commons.text.lookup.FunctionStringLookup", options0, "W)!A0p72^02y72mwh", false);
      OptionGroup optionGroup0 = new OptionGroup();
      options0.hasShortOption("org.apache.commons.io.file.SimplePathVisitor$AbstractBuilder");
      helpFormatter0.toSyntaxOptions(optionGroup0);
      helpFormatter1.getTableDefinition(collection0);
      helpFormatter1.getHelpAppendable();
      options0.toString();
      helpFormatter_Builder0.setComparator(helpFormatter0.DEFAULT_COMPARATOR);
      helpFormatter1.setSyntaxPrefix("cmdLineSyntax not provided");
      helpFormatter0.toSyntaxOptions((Iterable<Option>) collection0);
      helpFormatter1.getSyntaxPrefix();
      helpFormatter1.getOptionFormatBuilder();
      helpFormatter0.toSyntaxOptions((Iterable<Option>) collection0);
      helpFormatter0.toSyntaxOptions(options0);
      helpFormatter1.printOptions(options0);
      assertEquals("cmdLineSyntax not provided", helpFormatter1.getSyntaxPrefix());
      
      helpFormatter0.getComparator();
      helpFormatter0.sort((Iterable<Option>) collection0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      String string0 = null;
      boolean boolean0 = true;
      // Undeclared exception!
      try { 
        helpFormatter0.toSyntaxOptions((OptionGroup) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      helpFormatter_Builder0.setOptionGroupSeparator(" | ");
      LinkedHashSet<Option> linkedHashSet0 = new LinkedHashSet<Option>();
      TableDefinition tableDefinition0 = helpFormatter0.getTableDefinition(linkedHashSet0);
      helpFormatter0.printOptions(tableDefinition0);
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>();
      helpFormatter0.toSyntaxOptions((Iterable<Option>) priorityQueue0);
      helpFormatter0.printHelp("EwDMio", "aM`X$8S1", (Iterable<Option>) linkedHashSet0, "optionFormatBuilder", false);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      Comparator<Option> comparator0 = helpFormatter0.getComparator();
      helpFormatter_Builder0.setComparator(comparator0);
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      helpFormatter_Builder1.setHelpAppendable((HelpAppendable) null);
      HelpFormatter helpFormatter1 = new HelpFormatter(helpFormatter_Builder1);
      String string0 = helpFormatter1.getSyntaxPrefix();
      assertEquals("usage: ", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Class<Option> class0 = Option.class;
      ServiceLoader<Option> serviceLoader0 = ServiceLoader.load(class0);
      helpFormatter0.getTableDefinition(serviceLoader0);
      HelpAppendable helpAppendable0 = helpFormatter0.getHelpAppendable();
      helpFormatter_Builder0.setHelpAppendable(helpAppendable0);
      HelpFormatter helpFormatter1 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter1.printHelp("znQS,D'(/9eiT(][XR$", "", (Iterable<Option>) null, "znQS,D'(/9eiT(][XR$", false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      boolean boolean0 = true;
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      helpFormatter0.getSerializer();
      String string0 = null;
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      linkedList0.iterator();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      linkedList0.add(textStyle0);
      TreeSet<Option> treeSet0 = new TreeSet<Option>();
      List<Option> list0 = helpFormatter0.sort((Iterable<Option>) treeSet0);
      helpFormatter0.printOptions((Iterable<Option>) list0);
      Vector<String> vector0 = new Vector<String>();
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, linkedList0, vector0, (Iterable<List<String>>) null);
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions(tableDefinition0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.getHelpAppendable();
      String string0 = null;
      Options options0 = new Options();
      String string1 = null;
      helpFormatter_Builder0.setOptionFormatBuilder((OptionFormatter.Builder) null);
      boolean boolean0 = false;
      options0.addRequiredOption((String) null, "$)}Zgf*kEy~dT", false, "");
      Option option0 = null;
      try {
        option0 = new Option("", " | ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      HelpFormatter.builder();
      helpFormatter0.sort((Iterable<Option>) null);
      HelpFormatter.builder();
      helpFormatter_Builder0.setShowSince(false);
      String string0 = "";
      helpFormatter0.setSyntaxPrefix("");
      String string1 = "'o7";
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      Vector<String> vector0 = new Vector<String>();
      UnaryOperator<TextStyle> unaryOperator0 = UnaryOperator.identity();
      Function<Object, Integer> function0 = (Function<Object, Integer>) mock(Function.class, new ViolatedAssumptionAnswer());
      Function.identity();
      unaryOperator0.andThen((Function<? super TextStyle, ? extends Integer>) function0);
      arrayList0.replaceAll(unaryOperator0);
      HashSet<List<String>> hashSet0 = new HashSet<List<String>>(1, 1722.14F);
      // Undeclared exception!
      try { 
        hashSet0.toArray((Iterable<OptionGroup>[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      helpFormatter_Builder0.get();
      boolean boolean0 = true;
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder1);
      Comparator<Option> comparator0 = helpFormatter0.getComparator();
      helpFormatter_Builder1.setComparator(comparator0);
      HelpFormatter helpFormatter1 = helpFormatter_Builder1.get();
      Options options0 = new Options();
      helpFormatter1.toSyntaxOptions(options0);
      helpFormatter_Builder0.setOptionGroupSeparator("cmdLineSyntax not provided");
      Iterable<Option> iterable0 = null;
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = ".[_oLUF@]0l";
      Option option0 = new Option((String) null, ".[_oLUF@]0l", true, " | ");
      optionGroup0.setSelected(option0);
      OptionGroup optionGroup1 = optionGroup0.addOption(option0);
      helpFormatter0.toSyntaxOptions(optionGroup1);
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions((Iterable<Option>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      FileSystemHandling fileSystemHandling0 = new FileSystemHandling();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      helpFormatter0.getSerializer();
      OptionGroup optionGroup0 = new OptionGroup();
      Options options0 = new Options();
      helpFormatter0.toSyntaxOptions(options0);
      Option option0 = new Option((String) null, false, " | ");
      Option.builder();
      OptionGroup optionGroup1 = optionGroup0.addOption(option0);
      FileSystemHandling.appendLineToFile((EvoSuiteFile) null, (String) null);
      String string0 = helpFormatter0.toSyntaxOptions(optionGroup1);
      assertEquals("", string0);
      
      helpFormatter0.getComparator();
      String string1 = helpFormatter0.getOptionGroupSeparator();
      assertEquals(" | ", string1);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      List<Option> list0 = helpFormatter0.sort(options0);
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>(list0);
      HelpFormatter helpFormatter1 = helpFormatter_Builder0.get();
      Function<Option, OptionGroup> function0 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder0.setComparator(helpFormatter1.DEFAULT_COMPARATOR);
      helpFormatter1.toSyntaxOptions((Iterable<Option>) priorityQueue0, function0);
      OptionGroup optionGroup0 = new OptionGroup();
      options0.addOptionGroup(optionGroup0);
      Option option0 = new Option((String) null, (String) null, true, "{7lK");
      OptionFormatter optionFormatter0 = helpFormatter1.getOptionFormatter(option0);
      optionFormatter0.getArgName();
      OptionFormatter.Builder optionFormatter_Builder0 = new OptionFormatter.Builder(optionFormatter0);
      helpFormatter_Builder0.setOptionFormatBuilder(optionFormatter_Builder0);
      helpFormatter0.printOptions((Iterable<Option>) priorityQueue0);
      helpFormatter0.sort(options0);
      helpFormatter0.getComparator();
      String string0 = "comparator";
      String string1 = ">GW/)+G";
      String string2 = "org.apache.commons.text.lookup.UrlEncoderStringLookup";
      // Undeclared exception!
      try { 
        options0.addOption("", ", ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      Collection<Option> collection0 = options0.getOptions();
      helpFormatter0.toSyntaxOptions((Iterable<Option>) collection0);
      HelpFormatter.builder();
      helpFormatter0.sort(options0);
      options0.hasLongOption("'S/>n.xc2p<#md");
      HelpFormatter.builder();
      helpFormatter0.getHelpAppendable();
      helpFormatter0.setSyntaxPrefix("*eN_.=5Y4qL");
      helpFormatter0.toSyntaxOptions((Iterable<Option>) collection0);
      HelpFormatter.builder();
      helpFormatter0.getOptionFormatter((Option) null);
      helpFormatter0.toSyntaxOptions(options0);
      assertEquals("*eN_.=5Y4qL", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      OptionFormatter.Builder optionFormatter_Builder0 = OptionFormatter.builder();
      OptionFormatter.Builder optionFormatter_Builder1 = optionFormatter_Builder0.setDeprecatedFormatFunction((Function<Option, String>) null);
      OptionFormatter.Builder optionFormatter_Builder2 = optionFormatter_Builder1.setOptSeparator("");
      optionFormatter_Builder2.setDefaultArgName("");
      helpFormatter_Builder0.setOptionFormatBuilder(optionFormatter_Builder2);
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder1);
      helpFormatter0.getHelpAppendable();
      Options options0 = new Options();
      helpFormatter0.printOptions(options0);
      helpFormatter0.printHelp("p}", "", options0, " ", true);
      helpFormatter0.printOptions(options0);
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", "", options0, "%R:n<", false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      OptionFormatter.Builder optionFormatter_Builder0 = OptionFormatter.builder();
      optionFormatter_Builder0.toArgName("bC}KC1_VoC_p\"}a3");
      helpFormatter_Builder0.setOptionFormatBuilder(optionFormatter_Builder0);
      helpFormatter_Builder0.setComparator(helpFormatter0.DEFAULT_COMPARATOR);
      Function<Option, String> function0 = OptionFormatter.SIMPLE_DEPRECATED_FORMAT;
      optionFormatter_Builder0.setDeprecatedFormatFunction(function0);
      Options options0 = new Options();
      List<Option> list0 = helpFormatter0.sort(options0);
      BiFunction<OptionFormatter, Boolean, String> biFunction0 = (BiFunction<OptionFormatter, Boolean, String>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      optionFormatter_Builder0.setSyntaxFormatFunction(biFunction0);
      helpFormatter0.printOptions((Iterable<Option>) list0);
      helpFormatter0.setSyntaxPrefix("org.apache.commons.io.filefilter.DirectoryFileFilter");
      helpFormatter0.printOptions((Iterable<Option>) list0);
      List<Option> list1 = helpFormatter0.sort(options0);
      helpFormatter0.toSyntaxOptions((Iterable<Option>) list0);
      helpFormatter0.printHelp("5)zzEGC?8@?qrQm", "<bC}KC1_VoC_p\"}a3>", (Iterable<Option>) list1, "org.apache.commons.io.filefilter.DirectoryFileFilter", true);
      HelpFormatter.builder();
      helpFormatter0.getOptionFormatBuilder();
      helpFormatter0.getOptionFormatBuilder();
      assertEquals("org.apache.commons.io.filefilter.DirectoryFileFilter", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      
      helpFormatter0.setSyntaxPrefix("");
      assertEquals("", helpFormatter0.getSyntaxPrefix());
      
      LinkedList<Option> linkedList0 = new LinkedList<Option>();
      ArrayDeque<Option> arrayDeque0 = new ArrayDeque<Option>(linkedList0);
      helpFormatter0.getTableDefinition(arrayDeque0);
      helpFormatter0.getSyntaxPrefix();
      Option option0 = null;
      try {
        option0 = new Option(" | ", true, "0h~]");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal option name ' '.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      Options options0 = new Options();
      helpFormatter_Builder0.setShowSince(true);
      options0.hasShortOption("usage: ");
      List<Option> list0 = helpFormatter0.sort(options0);
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((String) null, "", (Iterable<Option>) list0, "", true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      helpFormatter0.toArgName("JKE;Y-8PLvNt!G;Q/?");
      helpFormatter0.toArgName(" ] [ long ");
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      helpFormatter_Builder0.setHelpAppendable(textHelpAppendable0);
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions((TableDefinition) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      Stack<Option> stack0 = new Stack<Option>();
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      stack0.forEach(consumer0);
      LinkedList<Option> linkedList0 = new LinkedList<Option>(stack0);
      linkedList0.containsAll(stack0);
      helpFormatter0.sort((Iterable<Option>) linkedList0);
      helpFormatter0.getComparator();
      helpFormatter_Builder1.setShowSince(false);
      linkedList0.parallelStream();
      helpFormatter_Builder0.setShowSince(false);
      Stack<Option> stack1 = new Stack<Option>();
      helpFormatter_Builder1.setShowSince(false);
      Option option0 = new Option("optionFormatBuilder", "optionFormatBuilder");
      Option.builder("optionFormatBuilder");
      stack1.add(option0);
      helpFormatter0.toSyntaxOptions((Iterable<Option>) stack1);
      stack1.add(option0);
      helpFormatter_Builder0.get();
      Options options0 = new Options();
      helpFormatter0.printOptions(options0);
      // Undeclared exception!
      try { 
        helpFormatter0.toSyntaxOptions((Iterable<Option>) stack1, (Function<Option, OptionGroup>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      Option option0 = new Option("SPl", "", true, "");
      Option.builder();
      options0.addOption(option0);
      options0.getOption("");
      OptionGroup optionGroup0 = new OptionGroup();
      Collection<Option> collection0 = optionGroup0.getOptions();
      helpFormatter0.printHelp("helpAppendable", "", (Iterable<Option>) collection0, "SPl", true);
      List<Option> list0 = helpFormatter0.sort(options0);
      Function<Option, OptionGroup> function0 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(function0).apply(any(org.apache.commons.cli.Option.class));
      helpFormatter0.toSyntaxOptions((Iterable<Option>) list0, function0);
      helpFormatter_Builder0.setShowSince(false);
      helpFormatter0.toArgName("+y ,7F9=%XC2psJ;D'");
      String string0 = helpFormatter0.toArgName("");
      assertEquals("<>", string0);
      
      Function<Option, OptionGroup> function1 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(function1).apply(any(org.apache.commons.cli.Option.class));
      String string1 = helpFormatter0.toSyntaxOptions((Iterable<Option>) list0, function1);
      assertEquals("[-SPl <arg>]", string1);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder1);
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>(helpFormatter0.DEFAULT_COMPARATOR);
      Option option0 = new Option("optionFormatBuilder", "");
      priorityQueue0.add(option0);
      helpFormatter0.sort((Iterable<Option>) priorityQueue0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      boolean boolean0 = true;
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      boolean boolean1 = true;
      helpFormatter_Builder1.setShowSince(true);
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder1);
      HelpFormatter helpFormatter1 = helpFormatter_Builder1.get();
      String string0 = "org.apache.commons.cli.help.AbstractHelpFormatter$Builder";
      HashSet<Option> hashSet0 = new HashSet<Option>(1);
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) hashSet0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      List<TextStyle> list0 = tableDefinition1.columnTextStyles();
      ArrayList<Locale.LanguageRange> arrayList0 = new ArrayList<Locale.LanguageRange>();
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.EXTENDED_FILTERING;
      List<String> list1 = Locale.filterTags((List<Locale.LanguageRange>) arrayList0, (Collection<String>) null, locale_FilteringMode0);
      HashSet<List<String>> hashSet1 = new HashSet<List<String>>();
      TableDefinition tableDefinition2 = TableDefinition.from("usage: ", list0, list1, hashSet1);
      // Undeclared exception!
      try { 
        helpFormatter1.printOptions(tableDefinition2);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      Class<Option> class0 = Option.class;
      OptionFormatter.Builder optionFormatter_Builder0 = helpFormatter0.getOptionFormatBuilder();
      OptionFormatter.Builder optionFormatter_Builder1 = optionFormatter_Builder0.setArgumentNameDelimiters((String) null, (String) null);
      OptionFormatter.Builder optionFormatter_Builder2 = optionFormatter_Builder1.setOptPrefix((String) null);
      optionFormatter_Builder2.setOptArgSeparator((String) null);
      helpFormatter_Builder0.setShowSince(false);
      Options options0 = new Options();
      OptionGroup optionGroup0 = new OptionGroup();
      options0.addOptionGroup(optionGroup0);
      helpFormatter_Builder0.setComparator(helpFormatter0.DEFAULT_COMPARATOR);
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((String) null, (String) null, options0, "e.m1-I~", false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      String string0 = helpFormatter0.toArgName("");
      assertEquals("<>", string0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      Options options0 = new Options();
      helpFormatter0.printOptions(options0);
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      TreeSet<Option> treeSet0 = new TreeSet<Option>();
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>((Collection<? extends Option>) treeSet0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) priorityQueue0);
      helpFormatter0.printOptions(tableDefinition0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Stack<List<String>> stack0 = new Stack<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, (List<TextStyle>) null, arrayList0, stack0);
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions(tableDefinition0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      Options options0 = new Options();
      options0.toString();
      options0.getOption(" | ");
      helpFormatter0.toSyntaxOptions(options0);
      Comparator<Option> comparator0 = helpFormatter0.getComparator();
      helpFormatter0.getSyntaxPrefix();
      helpFormatter_Builder1.setComparator(comparator0);
      HashSet<Option> hashSet0 = new HashSet<Option>(443);
      List<Option> list0 = helpFormatter0.sort((Iterable<Option>) hashSet0);
      hashSet0.add((Option) null);
      helpFormatter0.toSyntaxOptions((Iterable<Option>) list0, (Function<Option, OptionGroup>) null);
      hashSet0.parallelStream();
      helpFormatter0.getOptionFormatBuilder();
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setRequired(false);
      helpFormatter0.toSyntaxOptions(optionGroup0);
      hashSet0.add((Option) null);
      // Undeclared exception!
      try { 
        helpFormatter0.getTableDefinition(hashSet0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.OptionFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      helpFormatter0.toSyntaxOptions(optionGroup0);
      Vector<Option> vector0 = new Vector<Option>();
      Option option0 = null;
      try {
        option0 = new Option(" | ", "U9zG{", true, "C0$HF{");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal option name ' '.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      helpFormatter0.getComparator();
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      helpFormatter_Builder0.setOptionGroupSeparator("%s %s");
      OptionFormatter.Builder optionFormatter_Builder0 = OptionFormatter.builder();
      helpFormatter_Builder0.setOptionFormatBuilder(optionFormatter_Builder0);
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      LinkedList<Option> linkedList0 = new LinkedList<Option>();
      helpFormatter0.toSyntaxOptions((Iterable<Option>) linkedList0);
      helpFormatter0.getHelpAppendable();
      String string0 = helpFormatter0.getSyntaxPrefix();
      assertEquals("usage: ", string0);
      
      ArrayDeque<Option> arrayDeque0 = new ArrayDeque<Option>(linkedList0);
      helpFormatter0.printOptions((Iterable<Option>) arrayDeque0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder1);
      helpFormatter0.getHelpAppendable();
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>(helpFormatter0.DEFAULT_COMPARATOR);
      helpFormatter0.toSyntaxOptions((Iterable<Option>) priorityQueue0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      helpFormatter_Builder0.setHelpAppendable(textHelpAppendable0);
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      HelpFormatter.builder();
      helpFormatter0.getOptionFormatBuilder();
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      helpFormatter0.toSyntaxOptions(options0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder1);
      Options options0 = new Options();
      helpFormatter0.printHelp("&OeZ{&@w9I*nbmYb5*Z", "&OeZ{&@w9I*nbmYb5*Z", options0, ">,ef2cG8f", true);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      TreeSet<Option> treeSet0 = new TreeSet<Option>();
      TreeSet<Option> treeSet1 = new TreeSet<Option>((SortedSet<Option>) treeSet0);
      helpFormatter0.printHelp("{s%*yae&=l#5VUoYb", "RIGHT", (Iterable<Option>) treeSet1, "RIGHT", true);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((String) null, "Class %s not found, referenced in method %s", options0, (String) null, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      Options options0 = new Options();
      helpFormatter0.printOptions(options0);
      HelpFormatter.builder();
      String string0 = helpFormatter0.getSyntaxPrefix();
      assertEquals("usage: ", string0);
      
      OptionGroup optionGroup0 = new OptionGroup();
      Collection<Option> collection0 = optionGroup0.getOptions();
      helpFormatter0.getTableDefinition(collection0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      Comparator<Option> comparator0 = AbstractHelpFormatter.DEFAULT_COMPARATOR;
      helpFormatter_Builder1.setComparator(comparator0);
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder1);
      helpFormatter0.getOptionFormatBuilder();
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>();
      helpFormatter0.printOptions((Iterable<Option>) priorityQueue0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions((Iterable<Option>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setHelpAppendable((HelpAppendable) null);
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      helpFormatter_Builder0.setHelpAppendable(textHelpAppendable0);
      HelpFormatter.Builder helpFormatter_Builder2 = HelpFormatter.builder();
      assertNotSame(helpFormatter_Builder2, helpFormatter_Builder1);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      FileSystemHandling.createFolder((EvoSuiteFile) null);
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      OptionFormatter.Builder optionFormatter_Builder0 = OptionFormatter.builder();
      optionFormatter_Builder0.toArgName("bC}KC1_VoC_p\"}a3");
      helpFormatter_Builder0.setOptionFormatBuilder(optionFormatter_Builder0);
      helpFormatter_Builder0.setComparator(helpFormatter0.DEFAULT_COMPARATOR);
      Function<Option, String> function0 = OptionFormatter.SIMPLE_DEPRECATED_FORMAT;
      optionFormatter_Builder0.setDeprecatedFormatFunction(function0);
      Options options0 = new Options();
      List<Option> list0 = helpFormatter0.sort(options0);
      BiFunction<OptionFormatter, Boolean, String> biFunction0 = (BiFunction<OptionFormatter, Boolean, String>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      optionFormatter_Builder0.setSyntaxFormatFunction(biFunction0);
      helpFormatter0.printOptions((Iterable<Option>) list0);
      helpFormatter0.setSyntaxPrefix("org.apache.commons.io.filefilter.DirectoryFileFilter");
      helpFormatter0.printOptions((Iterable<Option>) list0);
      List<Option> list1 = helpFormatter0.sort((Options) null);
      helpFormatter0.toSyntaxOptions((Iterable<Option>) list0);
      helpFormatter0.printHelp("5)zzEGC?8@?qrQm", "<bC}KC1_VoC_p\"}a3>", (Iterable<Option>) list1, "org.apache.commons.io.filefilter.DirectoryFileFilter", true);
      HelpFormatter.builder();
      helpFormatter0.getOptionFormatBuilder();
      helpFormatter0.getOptionFormatBuilder();
      assertEquals("org.apache.commons.io.filefilter.DirectoryFileFilter", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      FileSystemHandling fileSystemHandling0 = new FileSystemHandling();
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      OptionFormatter.Builder optionFormatter_Builder0 = OptionFormatter.builder();
      OptionFormatter.Builder optionFormatter_Builder1 = optionFormatter_Builder0.setOptPrefix(":<!>'GMws2W<E5C'*");
      OptionFormatter.Builder optionFormatter_Builder2 = optionFormatter_Builder1.setOptArgSeparator(":<!>'GMws2W<E5C'*");
      Function<Option, String> function0 = OptionFormatter.COMPLEX_DEPRECATED_FORMAT;
      OptionFormatter.Builder optionFormatter_Builder3 = optionFormatter_Builder2.setDeprecatedFormatFunction(function0);
      optionFormatter_Builder2.build((Option) null);
      BiFunction<OptionFormatter, Boolean, String> biFunction0 = (BiFunction<OptionFormatter, Boolean, String>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      doReturn("kG:C{-D9Mj8f*\"").when(biFunction0).apply(any(org.apache.commons.cli.help.OptionFormatter.class) , anyBoolean());
      OptionFormatter.Builder optionFormatter_Builder4 = optionFormatter_Builder3.setSyntaxFormatFunction(biFunction0);
      optionFormatter_Builder1.setOptArgSeparator("w)-z 4HLCY-4_~|jye");
      optionFormatter_Builder4.setOptSeparator("%s %s");
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setOptionFormatBuilder(optionFormatter_Builder4);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Class<Option> class0 = Option.class;
      ServiceLoader<Option> serviceLoader0 = ServiceLoader.loadInstalled(class0);
      serviceLoader0.iterator();
      helpFormatter0.toSyntaxOptions((Iterable<Option>) serviceLoader0);
      Options options0 = new Options();
      helpFormatter0.sort(options0);
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setRequired(true);
      FileSystemHandling fileSystemHandling1 = new FileSystemHandling();
      Option option0 = new Option("$", false, "");
      OptionGroup optionGroup1 = optionGroup0.addOption(option0);
      optionGroup1.setSelected((Option) null);
      helpFormatter0.toSyntaxOptions(optionGroup1);
      helpFormatter0.getSyntaxPrefix();
      helpFormatter0.getHelpAppendable();
      HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder2 = HelpFormatter.builder();
      assertNotSame(helpFormatter_Builder2, helpFormatter_Builder1);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      boolean boolean0 = false;
      FileSystemHandling.setPermissions((EvoSuiteFile) null, false, false, false);
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      helpFormatter_Builder0.get();
      helpFormatter_Builder0.setOptionFormatBuilder((OptionFormatter.Builder) null);
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder1);
      Vector<Option> vector0 = new Vector<Option>(1);
      helpFormatter0.sort((Iterable<Option>) vector0);
      LinkedHashSet<Option> linkedHashSet0 = new LinkedHashSet<Option>(74);
      // Undeclared exception!
      try { 
        linkedHashSet0.forEach((Consumer<? super Option>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      Class<Option> class0 = Option.class;
      helpFormatter0.toArgName("org.apache.commons.text.similarity.LevenshteinResults");
      ServiceLoader<Option> serviceLoader0 = ServiceLoader.load(class0);
      helpFormatter0.toSyntaxOptions((Iterable<Option>) serviceLoader0);
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", "W", options0, "", false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      FileSystemHandling.appendStringToFile((EvoSuiteFile) null, "");
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder1);
      helpFormatter_Builder0.setOptionGroupSeparator("");
      Options options0 = new Options();
      helpFormatter_Builder1.setComparator(helpFormatter0.DEFAULT_COMPARATOR);
      helpFormatter0.toSyntaxOptions(options0);
      Vector<Option> vector0 = new Vector<Option>(5);
      OptionFormatter.Builder optionFormatter_Builder0 = OptionFormatter.builder();
      OptionFormatter.Builder optionFormatter_Builder1 = optionFormatter_Builder0.setLongOptPrefix("");
      helpFormatter_Builder1.setOptionFormatBuilder(optionFormatter_Builder1);
      Function<Option, OptionGroup> function0 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter0.toSyntaxOptions((Iterable<Option>) vector0, function0);
      helpFormatter0.getSerializer();
      String string0 = helpFormatter0.getOptionGroupSeparator();
      assertEquals(" | ", string0);
      
      OptionGroup optionGroup0 = new OptionGroup();
      helpFormatter0.toSyntaxOptions(optionGroup0);
      helpFormatter0.printHelp("@<L^_&%eWX#jk*okn<s", "", options0, "@<L^_&%eWX#j*okn<s", false);
      helpFormatter_Builder1.setShowSince(true);
      helpFormatter0.toSyntaxOptions(optionGroup0);
      String string1 = helpFormatter0.getSyntaxPrefix();
      assertEquals("usage: ", string1);
      
      helpFormatter0.toSyntaxOptions((Iterable<Option>) vector0);
      helpFormatter0.toSyntaxOptions((Iterable<Option>) vector0);
      helpFormatter0.getTableDefinition(vector0);
      helpFormatter0.toSyntaxOptions((Iterable<Option>) vector0);
      Function<Option, OptionGroup> function1 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter0.toSyntaxOptions((Iterable<Option>) vector0, function1);
      helpFormatter0.toSyntaxOptions((Iterable<Option>) vector0);
      String string2 = helpFormatter0.toArgName("");
      assertEquals("<>", string2);
      
      String string3 = helpFormatter0.toSyntaxOptions(options0);
      assertFalse(string3.equals((Object)string1));
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.getComparator();
      HelpFormatter helpFormatter1 = helpFormatter_Builder0.get();
      HelpFormatter helpFormatter2 = helpFormatter_Builder0.get();
      helpFormatter1.getOptionFormatBuilder();
      Options options0 = new Options();
      FileSystemHandling.appendLineToFile((EvoSuiteFile) null, " | ");
      HashSet<Option> hashSet0 = new HashSet<Option>(12);
      hashSet0.add((Option) null);
      OptionGroup optionGroup0 = new OptionGroup();
      Function<Option, OptionGroup> function0 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn(optionGroup0).when(function0).apply(any(org.apache.commons.cli.Option.class));
      HelpFormatter.builder();
      helpFormatter1.toSyntaxOptions((Iterable<Option>) hashSet0, function0);
      Function<Option, OptionGroup> function1 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn(optionGroup0).when(function1).apply(any(org.apache.commons.cli.Option.class));
      helpFormatter1.toSyntaxOptions((Iterable<Option>) hashSet0, function1);
      helpFormatter1.toSyntaxOptions(options0);
      helpFormatter2.toSyntaxOptions(options0);
      String string0 = helpFormatter2.getOptionGroupSeparator();
      assertEquals(" | ", string0);
      
      helpFormatter1.printHelp(" | ", " | ", options0, " | ", false);
      HelpFormatter.builder();
      helpFormatter1.getHelpAppendable();
      helpFormatter1.getOptionFormatBuilder();
      List<Option> list0 = helpFormatter2.sort((Iterable<Option>) hashSet0);
      helpFormatter0.getOptionFormatter((Option) null);
      HelpFormatter.builder();
      helpFormatter1.getOptionFormatBuilder();
      Function<Option, OptionGroup> function2 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn(optionGroup0).when(function2).apply(any(org.apache.commons.cli.Option.class));
      String string1 = helpFormatter0.toSyntaxOptions((Iterable<Option>) list0, function2);
      assertEquals("", string1);
      assertEquals("usage: ", helpFormatter2.getSyntaxPrefix());
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      options0.addRequiredOption((String) null, "usage: ", true, (String) null);
      List<Option> list0 = helpFormatter0.sort(options0);
      OptionFormatter.Builder optionFormatter_Builder0 = helpFormatter0.getOptionFormatBuilder();
      OptionFormatter.Builder optionFormatter_Builder1 = optionFormatter_Builder0.setLongOptPrefix("T");
      helpFormatter_Builder0.setOptionFormatBuilder(optionFormatter_Builder1);
      helpFormatter0.printHelp("w`2i**i3.f ", "5qT~ Kf;h", (Iterable<Option>) list0, (String) null, true);
      helpFormatter0.getTableDefinition(list0);
      assertEquals(1, list0.size());
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      HelpAppendable helpAppendable0 = helpFormatter0.getHelpAppendable();
      helpFormatter_Builder0.setHelpAppendable(helpAppendable0);
      helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter1 = new HelpFormatter(helpFormatter_Builder1);
      Options options0 = new Options();
      Stack<Option> stack0 = new Stack<Option>();
      options0.hasOption("");
      helpFormatter_Builder0.setComparator(helpFormatter1.DEFAULT_COMPARATOR);
      helpFormatter1.printHelp("org.apache.commons.text.lookup.FunctionStringLookup", "org.apache.commons.text.lookup.FunctionStringLookup", options0, "W)!A0p72^02y72mwh", false);
      FileSystemHandling.appendLineToFile((EvoSuiteFile) null, " | ");
      OptionGroup optionGroup0 = new OptionGroup();
      options0.hasShortOption("org.apache.commons.io.file.SimplePathVisitor$AbstractBuilder");
      helpFormatter0.toSyntaxOptions(optionGroup0);
      helpFormatter1.getTableDefinition(stack0);
      helpFormatter1.getHelpAppendable();
      options0.toString();
      HelpFormatter.builder();
      helpFormatter1.setSyntaxPrefix("cmdLineSyntax not provided");
      helpFormatter1.getSyntaxPrefix();
      helpFormatter1.getOptionFormatBuilder();
      helpFormatter0.toSyntaxOptions((Iterable<Option>) stack0);
      helpFormatter0.toSyntaxOptions(options0);
      helpFormatter1.printOptions(options0);
      assertEquals("cmdLineSyntax not provided", helpFormatter1.getSyntaxPrefix());
      
      helpFormatter0.getComparator();
      helpFormatter0.sort((Iterable<Option>) stack0);
      String string0 = helpFormatter0.toArgName("1I|B(");
      assertEquals("<1I|B(>", string0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      OptionGroup optionGroup0 = new OptionGroup();
      Option.builder();
      Options options0 = new Options();
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      ArrayList<Option> arrayList0 = new ArrayList<Option>();
      LinkedHashSet<Option> linkedHashSet0 = new LinkedHashSet<Option>(arrayList0);
      linkedHashSet0.spliterator();
      HelpFormatter.Builder helpFormatter_Builder1 = HelpFormatter.builder();
      assertNotSame(helpFormatter_Builder1, helpFormatter_Builder0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      helpFormatter_Builder0.setShowSince(false);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      helpFormatter_Builder0.setHelpAppendable(textHelpAppendable0);
      HelpFormatter.builder();
      HelpFormatter.builder();
      helpFormatter_Builder0.setShowSince(false);
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      Vector<String> vector0 = new Vector<String>();
      UnaryOperator<TextStyle> unaryOperator0 = UnaryOperator.identity();
      Function<Object, Integer> function0 = (Function<Object, Integer>) mock(Function.class, new ViolatedAssumptionAnswer());
      Function.identity();
      unaryOperator0.andThen((Function<? super TextStyle, ? extends Integer>) function0);
      FileSystemHandling.shouldAllThrowIOExceptions();
      HelpFormatter.builder();
      Options options0 = new Options();
      List<?> list0 = options0.getRequiredOptions();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      helpFormatter_Builder1.setOptionGroupSeparator("o/%9E^w[0v4wv443y");
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      helpFormatter0.getOptionGroupSeparator();
      helpFormatter_Builder1.setOptionGroupSeparator("usage: ");
      helpFormatter0.getSerializer();
      Option option0 = null;
      try {
        option0 = new Option("", false, "usage: ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }
}
