/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 20:36:54 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TextStyle_ESTest extends TextStyle_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      assertEquals(Integer.MAX_VALUE, textStyle_Builder0.getMaxWidth());
      
      textStyle_Builder0.setMaxWidth(0);
      TextStyle textStyle0 = textStyle_Builder0.get();
      textStyle0.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      assertEquals(0, textStyle_Builder0.getMaxWidth());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle textStyle0 = textStyle_Builder0.get();
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      textStyle0.pad(false, charBuffer0);
      assertEquals(Integer.MAX_VALUE, textStyle0.getMaxWidth());
      assertTrue(textStyle0.isScalable());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setMinWidth(1647);
      TextStyle textStyle0 = textStyle_Builder1.get();
      int int0 = textStyle0.getMinWidth();
      assertEquals(1647, textStyle_Builder0.getMinWidth());
      assertEquals(1647, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setMinWidth((-2204));
      TextStyle textStyle0 = textStyle_Builder0.get();
      int int0 = textStyle0.getMinWidth();
      assertEquals((-2204), textStyle_Builder0.getMinWidth());
      assertEquals((-2204), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      assertEquals(Integer.MAX_VALUE, textStyle_Builder0.getMaxWidth());
      
      textStyle_Builder0.setMaxWidth(0);
      TextStyle textStyle0 = textStyle_Builder0.get();
      int int0 = textStyle0.getMaxWidth();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setMaxWidth((-3795));
      TextStyle textStyle0 = textStyle_Builder0.get();
      int int0 = textStyle0.getMaxWidth();
      assertEquals((-3795), textStyle_Builder0.getMaxWidth());
      assertEquals((-3795), int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setLeftPad(5);
      TextStyle textStyle0 = textStyle_Builder0.get();
      int int0 = textStyle0.getLeftPad();
      assertEquals(5, textStyle_Builder0.getLeftPad());
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setLeftPad((-1260));
      TextStyle textStyle0 = textStyle_Builder1.get();
      int int0 = textStyle0.getLeftPad();
      assertEquals((-1260), textStyle_Builder0.getLeftPad());
      assertEquals((-1260), int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setIndent(897);
      TextStyle textStyle0 = textStyle_Builder0.get();
      int int0 = textStyle0.getIndent();
      assertEquals(897, textStyle_Builder0.getIndent());
      assertEquals(897, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setIndent((-1));
      TextStyle textStyle0 = textStyle_Builder0.get();
      int int0 = textStyle0.getIndent();
      assertEquals((-1), textStyle_Builder0.getIndent());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setIndent(Integer.MAX_VALUE);
      TextStyle textStyle0 = textStyle_Builder0.get();
      // Undeclared exception!
      textStyle0.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      // Undeclared exception!
      try { 
        textStyle0.DEFAULT.pad(false, (CharSequence) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextStyle", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setIndent((-2424));
      TextStyle textStyle0 = textStyle_Builder0.get();
      // Undeclared exception!
      try { 
        textStyle0.pad(true, "TextStyle{LEFT, l:0, i:-2424, false, min:0, max:unset}");
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle textStyle0 = textStyle_Builder0.get();
      String string0 = textStyle0.DEFAULT.toString();
      assertEquals(Integer.MAX_VALUE, textStyle0.getMaxWidth());
      assertEquals("TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}", string0);
      assertTrue(textStyle0.isScalable());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setMaxWidth(1647);
      TextStyle textStyle0 = textStyle_Builder0.get();
      String string0 = textStyle0.toString();
      assertEquals(1647, textStyle_Builder0.getMaxWidth());
      assertEquals("TextStyle{LEFT, l:0, i:0, true, min:0, max:1647}", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setMaxWidth(1647);
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder1.setIndent(1647);
      TextStyle textStyle0 = textStyle_Builder2.get();
      textStyle0.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      assertEquals(1647, textStyle_Builder1.getIndent());
      assertTrue(textStyle_Builder0.isScalable());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setMaxWidth(1647);
      TextStyle textStyle0 = textStyle_Builder1.get();
      textStyle0.pad(false, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      assertEquals(1647, textStyle_Builder0.getMaxWidth());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      textStyle_Builder0.setAlignment(textStyle_Alignment0);
      TextStyle textStyle0 = textStyle_Builder0.get();
      CharSequence charSequence0 = textStyle0.pad(true, "TextStyle{CENTER, l:0, i:0, true, min:0, max:unset}");
      assertTrue(textStyle0.isScalable());
      assertEquals("TextStyle{CENTER, l:0, i:0, true, min:0, max:unset}", charSequence0);
      assertEquals(Integer.MAX_VALUE, textStyle0.getMaxWidth());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setMaxWidth(1647);
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      textStyle_Builder0.setAlignment(textStyle_Alignment0);
      TextStyle textStyle0 = textStyle_Builder0.get();
      textStyle0.pad(true, "TextStyle{CENTER, l:0, i:0, true, min:0, max:1647}");
      assertEquals(1647, textStyle_Builder0.getMaxWidth());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      textStyle_Builder0.setAlignment(textStyle_Alignment0);
      TextStyle textStyle0 = textStyle_Builder0.get();
      CharSequence charSequence0 = textStyle0.pad(false, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      assertEquals(Integer.MAX_VALUE, textStyle0.getMaxWidth());
      assertEquals("TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}", charSequence0);
      assertTrue(textStyle0.isScalable());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setMaxWidth(1647);
      TextStyle textStyle0 = textStyle_Builder0.get();
      CharSequence charSequence0 = textStyle0.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle0.pad(true, charSequence0);
      assertEquals(1647, textStyle_Builder0.getMaxWidth());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      int int0 = textStyle_Builder0.getLeftPad();
      assertEquals(0, int0);
      assertTrue(textStyle_Builder0.isScalable());
      assertEquals(Integer.MAX_VALUE, textStyle_Builder0.getMaxWidth());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setTextStyle(textStyle0);
      assertSame(textStyle_Builder0, textStyle_Builder1);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.RIGHT;
      textStyle_Builder0.setAlignment(textStyle_Alignment0);
      TextStyle textStyle0 = textStyle_Builder0.get();
      textStyle0.pad(false, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      assertEquals(Integer.MAX_VALUE, textStyle0.getMaxWidth());
      assertTrue(textStyle0.isScalable());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      int int0 = textStyle_Builder0.getMinWidth();
      assertEquals(0, int0);
      assertTrue(textStyle_Builder0.isScalable());
      assertEquals(Integer.MAX_VALUE, textStyle_Builder0.getMaxWidth());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      int int0 = textStyle_Builder0.getIndent();
      assertEquals(Integer.MAX_VALUE, textStyle_Builder0.getMaxWidth());
      assertTrue(textStyle_Builder0.isScalable());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      assertTrue(textStyle_Builder0.isScalable());
      
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setScalable(false);
      TextStyle textStyle0 = textStyle_Builder1.get();
      boolean boolean0 = textStyle0.isScalable();
      assertFalse(textStyle_Builder0.isScalable());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      boolean boolean0 = textStyle_Builder0.isScalable();
      assertEquals(Integer.MAX_VALUE, textStyle_Builder0.getMaxWidth());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      int int0 = textStyle_Builder0.getMaxWidth();
      assertTrue(textStyle_Builder0.isScalable());
      assertEquals(Integer.MAX_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle textStyle0 = textStyle_Builder0.get();
      int int0 = textStyle0.getMinWidth();
      assertTrue(textStyle0.isScalable());
      assertEquals(0, int0);
      assertEquals(Integer.MAX_VALUE, textStyle0.getMaxWidth());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle textStyle0 = textStyle_Builder0.get();
      int int0 = textStyle0.getIndent();
      assertEquals(Integer.MAX_VALUE, textStyle0.getMaxWidth());
      assertTrue(textStyle0.isScalable());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle textStyle0 = textStyle_Builder0.get();
      int int0 = textStyle0.getMaxWidth();
      assertTrue(textStyle0.isScalable());
      assertEquals(Integer.MAX_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      int int0 = textStyle0.getLeftPad();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      TextStyle.Alignment textStyle_Alignment0 = textStyle0.getAlignment();
      assertEquals(TextStyle.Alignment.LEFT, textStyle_Alignment0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle textStyle0 = textStyle_Builder0.get();
      boolean boolean0 = textStyle0.isScalable();
      assertEquals(Integer.MAX_VALUE, textStyle0.getMaxWidth());
      assertTrue(boolean0);
  }
}
