/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 20:51:40 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.PriorityQueue;
import java.util.Stack;
import java.util.TreeSet;
import java.util.Vector;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TableDefinition_ESTest extends TableDefinition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      PriorityQueue<List<String>> priorityQueue0 = new PriorityQueue<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("org.apache.commons.cli.help.TableDefinition$1", (List<TextStyle>) null, linkedList0, priorityQueue0);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNotNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      Vector<Locale.LanguageRange> vector1 = new Vector<Locale.LanguageRange>();
      ArrayDeque<String> arrayDeque0 = new ArrayDeque<String>();
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) vector1, (Collection<String>) arrayDeque0);
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, vector0, list0, (Iterable<List<String>>) null);
      List<String> list1 = tableDefinition0.headers();
      assertTrue(list1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      Vector<String> vector1 = new Vector<String>();
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>();
      vector1.add("org.apache.commons.cli.help.TableDefinition$1");
      TableDefinition tableDefinition0 = TableDefinition.from("org.apache.commons.cli.help.TableDefinition$1", vector0, vector1, treeSet0);
      List<String> list0 = tableDefinition0.headers();
      assertTrue(list0.contains("org.apache.commons.cli.help.TableDefinition$1"));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      PriorityQueue<List<String>> priorityQueue0 = new PriorityQueue<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("org.apache.commons.cli.help.TableDefinition$1", (List<TextStyle>) null, linkedList0, priorityQueue0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Vector<Option> vector0 = new Vector<Option>();
      ArrayList<Option> arrayList0 = new ArrayList<Option>(vector0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) arrayList0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertEquals(8, list0.size());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      Vector<Locale.LanguageRange> vector1 = new Vector<Locale.LanguageRange>();
      ArrayDeque<String> arrayDeque0 = new ArrayDeque<String>();
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) vector1, (Collection<String>) arrayDeque0);
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, vector0, list0, (Iterable<List<String>>) null);
      String string0 = tableDefinition0.caption();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      ArrayList<Option> arrayList0 = new ArrayList<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) arrayList0);
      String string0 = tableDefinition0.caption();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      TableDefinition tableDefinition0 = TableDefinition.from("r", stack0, (List<String>) null, (Iterable<List<String>>) null);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      TableDefinition tableDefinition0 = TableDefinition.from("r", stack0, (List<String>) null, (Iterable<List<String>>) null);
      String string0 = tableDefinition0.caption();
      assertEquals("r", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      TableDefinition tableDefinition0 = TableDefinition.from("r", stack0, (List<String>) null, (Iterable<List<String>>) null);
      List<String> list0 = tableDefinition0.headers();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      TableDefinition tableDefinition0 = TableDefinition.from("r", stack0, (List<String>) null, (Iterable<List<String>>) null);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertTrue(list0.isEmpty());
  }
}
