/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 20:49:15 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.PrintStream;
import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.Charset;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.PriorityQueue;
import java.util.Queue;
import java.util.Stack;
import java.util.Vector;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.FilterHelpAppendable;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextHelpAppendable;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FilterHelpAppendable_ESTest extends FilterHelpAppendable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      TextHelpAppendable.systemOut();
      Stack<Queue<String>> stack0 = new Stack<Queue<String>>();
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      // Undeclared exception!
      try { 
        textHelpAppendable0.append('2');
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.getTextStyleBuilder();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>();
      LinkedHashSet<Option> linkedHashSet0 = new LinkedHashSet<Option>(priorityQueue0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) linkedHashSet0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      ArrayDeque<List<String>> arrayDeque0 = new ArrayDeque<List<String>>();
      Vector<List<String>> vector0 = new Vector<List<String>>(arrayDeque0);
      TableDefinition.from("", list0, arrayList0, vector0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      textHelpAppendable0.appendTable(tableDefinition1);
      CharBuffer charBuffer0 = CharBuffer.allocate(136209934);
      // Undeclared exception!
      textHelpAppendable0.append((CharSequence) charBuffer0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      int int0 = (-1393);
      CharBuffer charBuffer0 = CharBuffer.allocate(3);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) charBuffer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      String string0 = "";
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      LinkedList<String> linkedList1 = new LinkedList<String>();
      Iterable<List<String>> iterable0 = null;
      textHelpAppendable0.append((CharSequence) "", 0, 0);
      int int0 = 3481;
      // Undeclared exception!
      try { 
        CharBuffer.wrap((char[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      CharBuffer charBuffer0 = CharBuffer.allocate(4);
      int int0 = 0;
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) charBuffer0, 4, 0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.HeapCharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MockPrintStream mockPrintStream0 = new MockPrintStream("[:U/@00HRK^vXURU?<g");
      MockPrintStream mockPrintStream1 = new MockPrintStream(mockPrintStream0, false);
      Object[] objectArray0 = new Object[7];
      objectArray0[0] = (Object) ";b}Pu`B^AV*O&E";
      objectArray0[1] = (Object) "[:U/@00HRK^vXURU?<g";
      objectArray0[2] = (Object) ";b}Pu`B^AV*O&E";
      objectArray0[3] = (Object) mockPrintStream0;
      objectArray0[4] = (Object) mockPrintStream1;
      objectArray0[5] = (Object) "[:U/@00HRK^vXURU?<g";
      objectArray0[6] = (Object) ";b}Pu`B^AV*O&E";
      PrintStream printStream0 = mockPrintStream1.format(";b}Pu`B^AV*O&E", objectArray0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(printStream0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) ";b}Pu`B^AV*O&E", (-3964), 1);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.append('Z');
      FilterHelpAppendable filterHelpAppendable0 = textHelpAppendable0.append('Z');
      assertSame(textHelpAppendable0, filterHelpAppendable0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MockPrintStream mockPrintStream0 = new MockPrintStream("org.apache.commons.cli.help.FilterHelpAppendable");
      PrintStream printStream0 = mockPrintStream0.append('/');
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(printStream0);
      textHelpAppendable0.appendHeader(666, "org.apache.commons.cli.help.FilterHelpAppendable");
      mockPrintStream0.print((-1.0F));
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textHelpAppendable0.printWrapped("org.apache.commons.cli.help.FilterHelpAppendable", textStyle0);
      textHelpAppendable0.getMaxWidth();
      FilterHelpAppendable filterHelpAppendable0 = textHelpAppendable0.append((CharSequence) "org.apache.commons.cli.help.FilterHelpAppendable");
      // Undeclared exception!
      try { 
        filterHelpAppendable0.append((CharSequence) "org.apache.commons.cli.help.FilterHelpAppendable", 74, 7);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textHelpAppendable0.printWrapped("h]1g'", textStyle0);
      assertEquals(Integer.MAX_VALUE, textStyle0.getMaxWidth());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      int int0 = textHelpAppendable0.getLeftPad();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      FilterHelpAppendable filterHelpAppendable0 = textHelpAppendable0.append('o');
      filterHelpAppendable0.append((CharSequence) "Q@B-of+N.Q1=,?-gFB}", 7, 7);
      textHelpAppendable0.appendTitle("Q@B-of+N.Q1=,?-gFB}");
      assertSame(textHelpAppendable0, filterHelpAppendable0);
  }
}
